# -*- coding: utf-8 -*-
"""RoadGuardModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBWDbdvXDD6DwUcYuhVBI58B0ECUm7_9
"""

!pip install ultralytics
!pip install opencv-python

"""## Load the datasets"""

from google.colab import files
import zipfile

uploaded = files.upload()

dataset_zip = 'road_guard.zip'
with zipfile.ZipFile(dataset_zip, 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

"""## Import the YOLO Model"""

from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model.train(data='/content/dataset/data.yaml',
            epochs=50,
            imgsz=640,
            batch=16,
            name='yolo_custom')

"""## Evaluted the Model"""

results = model.val()

y_true = results.classification['gt']
y_pred = results.classification['pred']

"""## Confussion Matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

conf_matrix = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix for YOLOv8 Predictions')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

"""## Print the accuracy"""

accuracy = results.box['accuracy']
print(f"Accuracy: {accuracy}")